### PR TITLE
Fix: better (Redis) exception handling

### LINKED ISSUE #88: handle generic (unwrapped) errors from Redis
such as: `IOError`, otherwise these willl propagate out and crash the pipeline:
```
[ERROR][logstash.javapipeline    ][mq][f669cc10d01329b13e936073a827724110f2c178c852cebfd2d8d3f80a58141c] A plugin had an unrecoverable error. Will restart this plugin.
  Pipeline_id:loggermq
  Plugin: <LogStash::Inputs::Redis host=>"some.host", data_type=>"list", id=>"redis", key=>"foo", enable_metric=>true, codec=><LogStash::Codecs::JSON id=>"json_6227b920-d3b8-4380-a469-ee7d9949a208", enable_metric=>true, charset=>"UTF-8">, threads=>1, port=>6379, ssl=>false, db=>0, timeout=>5, batch_count=>125>
  Error: closed stream
  Exception: IOError
  Stack: org/jruby/RubyIO.java:1366:in `write_nonblock'
/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/redis-4.2.5/lib/redis/connection/ruby.rb:76:in `block in write'
org/jruby/RubyKernel.java:1442:in `loop'
/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/redis-4.2.5/lib/redis/connection/ruby.rb:75:in `write'
/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/redis-4.2.5/lib/redis/connection/ruby.rb:374:in `write'
/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/redis-4.2.5/lib/redis/client.rb:289:in `block in write'
/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/redis-4.2.5/lib/redis/client.rb:268:in `io'
/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/redis-4.2.5/lib/redis/client.rb:287:in `write'
/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/redis-4.2.5/lib/redis/client.rb:245:in `block in process'
org/jruby/RubyArray.java:1809:in `each'
/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/redis-4.2.5/lib/redis/client.rb:239:in `block in process'
/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/redis-4.2.5/lib/redis/client.rb:389:in `ensure_connected'
/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/redis-4.2.5/lib/redis/client.rb:238:in `block in process'
/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/redis-4.2.5/lib/redis/client.rb:344:in `logging'
/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/redis-4.2.5/lib/redis/client.rb:237:in `process'
/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/redis-4.2.5/lib/redis/client.rb:131:in `call'
/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/redis-4.2.5/lib/redis.rb:2585:in `block in _eval'
/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/redis-4.2.5/lib/redis.rb:69:in `block in synchronize'
uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/monitor.rb:235:in `mon_synchronize'
/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/redis-4.2.5/lib/redis.rb:69:in `synchronize'
/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/redis-4.2.5/lib/redis.rb:2584:in `_eval'
/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/redis-4.2.5/lib/redis.rb:2636:in `evalsha'
/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-input-redis-3.5.1/lib/logstash/inputs/redis.rb:222:in `list_batch_listener'
org/jruby/RubyMethod.java:123:in `call'
/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-input-redis-3.5.1/lib/logstash/inputs/redis.rb:208:in `list_runner'
org/jruby/RubyMethod.java:119:in `call'
/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-input-redis-3.5.1/lib/logstash/inputs/redis.rb:104:in `run'
:1:in `'
/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:396:in `block in start_input'
```

### PR DESCRIPTION
**Pull request by kares**
Redis doesn't wrap all of the errors e.g. (retriable) `IOError` might be raised from an IO write (https://github.com/logstash-plugins/logstash-input-redis/issues/88).
With the refactored error handling we make sure these are logged and retried instead of causing pipeline crashes.

Also not all specs from the suite were run on the CI, as some are tagged with `redis`.
These require a real Redis server, no reason not to run them against CI as well.

*NOTE: extracted from https://github.com/logstash-plugins/logstash-input-redis/pull/87 except the problematic subscription 'interrupting' bits (which are still pending)*

resolves #88

### CODE REVIEW

File: lib/logstash/inputs/redis.rb [hunk 1]
```diff
@@ -268,15 +262,39 @@ def redis_runner
...
       @redis ||= connect
       yield
-    rescue ::Redis::BaseError => e
-      @logger.warn("Redis connection problem", :exception => e)
-      # Reset the redis variable to trigger reconnect
-      @redis = nil
-      Stud.stoppable_sleep(1) { stop? }
-      retry if !stop?
+    rescue => e
+      retry unless handle_error(e)
```
Comment (kaisecheng) [inline lib/logstash/inputs/redis.rb:266]: A suggestion to rename `handle_error`
I can understand you want to retry when `handle_error` cannot handle, meaning return false
Looking at the whole function, we actually want to retry when it is retryable error, somehow meaning we can handle it, so it is a bit confusing at the first look.

may be we can do `retry handle_error(e)` or `retry retryable_error(e)` ?

**Review by kaisecheng — COMMENTED** [review]
I left a comment for the method name. 
Can you check the red CI?

File: lib/logstash/inputs/redis.rb (hunk 1 above)
Comment (kares) [reply lib/logstash/inputs/redis.rb:266]: yeah, no super clear - also struggled a bit with naming here.
we're trying to re-use this method as much as possible.
so `handle_error` returns `true` if error is handled and should not be retried :wink: 

I guess you meant `retry if handle_error(e)`, 
that is actually what I started with but the inverse boolean condition [confused someone else](https://github.com/logstash-plugins/logstash-input-redis/pull/87/files/b19e1d9d54888bec9986530c623611fddab8bf64#r612638240) :rofl:

File: lib/logstash/inputs/redis.rb [hunk 2]
```diff
@@ -248,18 +240,20 @@ def list_single_listener(redis, output_queue)
...
       if @data_type == 'pattern_channel'
-        @redis.punsubscribe
+        redis.punsubscribe
       else
-        @redis.unsubscribe
+        redis.unsubscribe
       end
     else
-      @redis.disconnect!
+      redis.disconnect!
```
Comment (robbavey) [inline lib/logstash/inputs/redis.rb:253]: This commit removes this comment:

```
 if its a SubscribedClient then:
    # it does not have a disconnect method (yet)
```

It feels like there is some context missing as to why `disconnect!` is not called when redis is subscribed, if this is indeed still the desired behaviour.

File: lib/logstash/inputs/redis.rb (hunk 1 above)
Comment (robbavey) [reply lib/logstash/inputs/redis.rb:266]: I think `retry unless handle_error` is ok - another way you could possibly handle this is to just have the new method a no side effect logging method, like `log_error(e)`, which just deals with the formatting/logging keeping the actual retry logic (with the `ShutdownSignal` special case) local

**Review by robbavey — COMMENTED** [review]
Some minor comments

File: lib/logstash/inputs/redis.rb (hunk 1 above)
Comment (kares) [reply lib/logstash/inputs/redis.rb]: thanks, split the method into two. 
still needed some kind of `retry if ...` as the logic is at two places - did not want to have the same logic inline twice.
esp. since looking at the plugin the first time I manage to miss the "other" error handling place initially.

let's see what @kaisecheng thinks :crossed_fingers:

File: lib/logstash/inputs/redis.rb (hunk 2 above)
Comment (kares) [reply lib/logstash/inputs/redis.rb]: believe this was a left over from the Redis 3.x days. 
[`Redis#disconnect`](https://github.com/redis/redis-rb/blob/v4.0.1/lib/redis.rb#L67) is always fine to call (in 4.x) regardless of the `@client` used (`@original_client` is never "replaced").

also no reason not to have disconnect (`close`) here, I've updated the PR - thanks for the hint.

File: lib/logstash/inputs/redis.rb (hunk 1 above)
Comment (kaisecheng) [reply lib/logstash/inputs/redis.rb]: This is much better. Splitting to two is great 👏 .  The naming and comment help a lot. Thanks for doing it.

**Review by kaisecheng — APPROVED** [review]
LGTM  :fairy:

**Review by robbavey — APPROVED** [review]
LGTM
